### ISSUE TITLE
Piwik Android sdk - why custom variables are deprecated? can we still use them?

### ISSUE THREAD

**Issue by bhardwajvinay4** [matomo-org/piwik-sdk-android#192]
Piwik Android sdk - why custom variables are deprecated? can we still use them?

**Comment by d4rken** [comment]
https://matomo.org/faq/general/faq_21117/

**Comment by d4rken** [comment]
Yes you can still use them, but if you are starting from scratch is recommended to use custom dimensions.

**Comment by bhardwajvinay4** [comment]
Thanks Matthias.
