### ISSUE TITLE
Failed resolution of: Ltimber/log/Timber

### ISSUE THREAD

**Issue by amiralichesser3** [matomo-org/piwik-sdk-android#193]
I cant seem to be able to resolve Timber

**Comment by d4rken** [comment]
Add `implementation 'com.jakewharton.timber:timber:4.6.0'` to your `build.gradle`

#184

**Comment by GitHubMurt** [comment]
I have a project called myProject. I put it to myProject "lib" folder another project called myLib.aar.
myLib project contains Timber.
api 'com.jakewharton.timber:timber:4.7.1'


when i try to build myProject i got:
java.lang.NoClassDefFoundError: Failed resolution of: Ltimber/log/Timber$DebugTree;
