### ISSUE TITLE
Why Timber is included in release?

### ISSUE THREAD

**Issue by elevenetc** [matomo-org/piwik-sdk-android#204]
Getting an exception:
```
java.lang.NoClassDefFoundError: Failed resolution of: Ltimber/log/Timber;
```
Why `Timber` is in released version of library? It's assumed that every developer uses `Timber`? Using `3.0.1` version.

**Comment by d4rken** [comment]
I'll try to reproduce this. Possibly related to #184

**Comment by d4rken** [comment]
Hmmm

https://github.com/bintray/gradle-bintray-plugin/issues/197
