### ISSUE TITLE
Should app id be an int or a string?

### ISSUE THREAD

**Issue by tomvo** [matomo-org/piwik-sdk-android#205]
The docs state that the app id for the `TrackerConfig` constructor should be an int, however the only id's I can find in my website configurations are UUID's like: `1ef8a846-8a00-447b-a6cc-5f6e......`.

**Comment by d4rken** [comment]
It's an int.

Check `Settings>Manage Websites` in your server.

If this is the only site on your server, then it is likely `1`. You can also see `idSite=1` within the URLs when browsing it.

**Comment by tomvo** [comment]
@d4rken Ah yes, got it. Thanks!
