### ISSUE TITLE
Custom dimension not working

### ISSUE THREAD

**Issue by Yetispapa** [matomo-org/piwik-sdk-android#214]
I'm facing the problem that I don't get any dimension-informations. As I understand the documentation correctly I have to set the dimensions everytime an event is fired (or in my case when I'm firing an event). By the way the event itself is working only the dimension are not tracked. This is my code:

```
TrackHelper.track()
                .dimension(1, DeviceInformation.getAndroidVersion())
                .dimension(2, DeviceInformation.getModel())
                .event(category, action).with(this.tracker);
```

Can someone confirm my code or am I wrong about setting the dimensions everytime?

**Comment by d4rken** [comment]
Closed due to inactivity. Feel free to reopen this if this is still an ongoing issue.
