### ISSUE TITLE
 invokedynamic requires --min-sdk-version >= 26

### ISSUE THREAD

**Issue by cs8** [matomo-org/piwik-sdk-android#216]
I use the  globalMinSdkVersion = 19 but bulid failed.
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

**Comment by d4rken** [comment]
Closed due to inactivity. Feel free to reopen this if this is still an ongoing issue.

**Comment by mann579** [comment]
Can we reopen this?
