### ISSUE TITLE
Campaign tracking

### ISSUE THREAD

**Issue by ThomasGoehringer** [matomo-org/piwik-sdk-android#218]
I tried to add campaign tracking to my Android app. As there is no explicit method for that I tried to pass my own TrackMe object on the track method. On the object I set QueryParams.CAMPAIGN_NAME and QueryParams.CAMPAIGN_KEYWORD. However I can't find these values being tracked as campaign parameters.
Am I doing something wrong or is this not supported yet?

**Comment by d4rken** [comment]
Have you checked whether the parameters are transmitted?

It's also possible that just those two keywords are not enough for the server, e.g. you'd need to also send in a tracked event or page view.

**Comment by ThomasGoehringer** [comment]
I think it has to be set like the user ID. I'll have a try extending the SDK and create a PR if it works.

**Comment by d4rken** [comment]
> _rcn — The Campaign name (see Tracking Campaigns). Used to populate the Referrers > Campaigns report. Note: this parameter will only be used for the first pageview of a visit.
> _rck — The Campaign Keyword (see Tracking Campaigns). Used to populate the Referrers > Campaigns report (clicking on a campaign loads all keywords for this campaign). Note: this parameter will only be used for the first pageview of a visit.

You could be right about that. This reads like you need to set these parameters on the initial trackme that's the first contact with the API for a visit.

**Comment by ThomasGoehringer** [comment]
Have a look at my PR. This works for me.

**Comment by d4rken** [comment]
@ThomasGoehringer I think we can close this, right?
