### ISSUE TITLE
CRLF Injection - Improper Output Neutralization for Logs

### ISSUE THREAD

**Issue by ishwarverma39** [matomo-org/piwik-sdk-android#222]
Hi, team we are using Piwik for our Android applications. 
We are getting these security vulnerabilities when doing the security scanning.

Source file names are
DefaultPacketSender.java  -   org/piwik/sdk/dispatcher/
Tracker.java    -   org/piwik/sdk/

Method name is void **zzk(android.content.Intent)**

Please advise how to resolve this issue.

**Comment by d4rken** [comment]
There is no method with that signature in either class.

Imho, CRLF Injection is not really a concern here. This library doesn't log by default. If this is a security issue for your project and you require logging then you can write a custom `Tree` for the logging library `Timber` used here, that escapes CRLF sequences.
