### ISSUE TITLE
No data being sent to server

### ISSUE THREAD

**Issue by ejo4041** [matomo-org/piwik-sdk-android#225]
I have been following the README closely and implementing a simple test app to get data to a test Matomo instance locally.  I can access the Matomo web UI through a browser no problem, but it just shows the no data screen like the app has never reached it.

Here is my code:

```
public class MainActivity extends Activity {

    private String TAG = MainActivity.class.getSimpleName();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Timber.plant(new Timber.DebugTree());
        Log.d(TAG, "about to track");
        Tracker tracker = ((PiwikTracker) getApplication()).getTracker(); //PiwikTracker.getTracker(this.getApplicationContext());
        TrackHelper.track().screen("/MainActivity").title("PiwikTestApp").with(tracker);
        TrackHelper.track().event("/MainActivity", "opened").with(tracker);

        // Monitor your app installs
        TrackHelper.track().download().with(tracker);
        Log.d(TAG, "done tracking");
```

And here is the PiwikTracker code:
```
public class PiwikTracker extends Application {
    private Tracker mPiwikTracker;
    private String TAG = PiwikTracker.class.getSimpleName();

    public synchronized Tracker getTracker() {

        if (mPiwikTracker != null) return mPiwikTracker;
        Log.d(TAG, "Making new tracker");
        String serverAddress = "https://URL/piwik.php";
        String tracker = "PiwikTestApp";
        mPiwikTracker = Piwik.getInstance(this).newTracker(new TrackerConfig(serverAddress, 2, tracker));
        return mPiwikTracker;
    }
}
```

The app starts, and there are no clear errors during execution.  I have tried a more recent version, but it was not compatible with my phone OS (Android 23), so I rolled back to:
```
dependencies {
    implementation 'org.piwik.sdk:piwik-sdk:2.0.0''

```

**Comment by bruceweir** [comment]
Check that your Matomo Dashboard is set to filter on the correct date. It can default to the previous day, which can make it look like it has no data when you first start using it.

**Comment by ejo4041** [comment]
I have since gotten a new phone and am now using 3.0.3.
I have gone to the all website dashboard and expanded to a year, still nothing.

This is crashing the app, so I am taking it out for now, I just need to get somthing working.
`TrackHelper.track().download().with(tracker);`

I can paste the tombstone from that one if it is useful.

**Comment by ejo4041** [comment]
I guess I was not being patient enough for the default 120 second dispatch.  After setting it to 0, I see it trying to send now, but it is not getting through.  When I send to HTTP, I get this:

```
2018-11-12 10:57:12.849 23329-23355/com.android.piwiktestapp E/PIWIK:DefaultPacketSender: Transmission failed unexpectedly.
    java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at org.piwik.sdk.dispatcher.DefaultPacketSender.send(DefaultPacketSender.java:102)
        at org.piwik.sdk.dispatcher.DefaultDispatcher$1.run(DefaultDispatcher.java:179)
        at java.lang.Thread.run(Thread.java:764)
```


When I try to send to HTTPS, I get:
`2018-11-12 11:02:33.497 23545-23575/com.android.piwiktestapp E/PIWIK:DefaultPacketSender: Transmission failed unexpectedly.
    javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)`

The HTTPS, I am certain is because we have a self signed cert.  I haven't found anywhere to add it to the connection yet though.

**Comment by d4rken** [comment]
> This is crashing the app, so I am taking it out for now, I just need to get somthing working.
TrackHelper.track().download().with(tracker);

If that's caused by this lib, make another issue ticket please.

> After setting it to 0, I see it trying to send now, but it is not getting through. When I send to HTTP, I get this: (...)

Seems the server gave a non successful error code (something else then 200 or 204) but then the error stream is still null. Here it would be interesting what the servers response was.

> The HTTPS, I am certain is because we have a self signed cert. I haven't found anywhere to add it to the connection yet though.

You'd have to write a (or modify the default) `PacketSender` and make it use your cert I think.  You can then tell the library to use it by supplying it[ here](https://github.com/matomo-org/piwik-sdk-android/blob/a3c0a4189f58ec88199bf54b74f5bf84a722edba/piwik-sdk/src/main/java/org/piwik/sdk/dispatcher/DefaultDispatcherFactory.java).

Maybe it easier to just not use a self-signed cert? You can can get free ones from [Let's Encrypt](https://letsencrypt.org/) which is what I have done.

**Comment by ejo4041** [comment]
I will open a bug for the other issue.

I created my own PacketSender and DispatcherFactory using a HttpsURLConnection and now it hits the server, thanks!

**Comment by d4rken** [comment]
I guess this can be closed then?

**Comment by d4rken** [comment]
Continued in #229
