### ISSUE TITLE
W/OkHttpClient: A connection to https://xxx.com/ was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by findById** [matomo-org/piwik-sdk-android#226]
```
Timber.tag(LOGGER_TAG).v("Transmission succesful (code=%d).", statusCode);
// add fix code in org.piwik.sdk.dispatcher.DefaultPacketSender#97 (start)
try {
    if (statusCode == HttpURLConnection.HTTP_OK) {
        // fix W/OkHttpClient: A connection to https://xxx.com/ was leaked. Did you forget to close a response body?
        InputStream is = urlConnection.getInputStream();
        if (is != null) {
            is.close();
        }
    }
} catch (Throwable ignore) {
}
// add fix code end
```

**Comment by d4rken** [comment]
Link to the specific section

https://github.com/matomo-org/piwik-sdk-android/blob/2638439e19aa08979ecfa0e20c58f5c653436218/piwik-sdk/src/main/java/org/piwik/sdk/dispatcher/DefaultPacketSender.java#L95

So this is likely a bug, good catch :+1: 

While the Android documentation [does not mention](https://developer.android.com/reference/java/net/HttpURLConnection) in it's example that the input stream needs to be explicitly closed, they read the inputstream completely.

So as far as I understood it you either need to read the input stream completely, at which point `HttpURLConnection.disconnect()` will close it  or explicitly close it beforehand.

* https://stackoverflow.com/questions/4767553/safe-use-of-httpurlconnection
* https://stackoverflow.com/questions/11056088/do-i-need-to-call-httpurlconnection-disconnect-after-finish-using-it
* https://stackoverflow.com/questions/3460990/httpurlconnection-implementation
