### ISSUE TITLE
More transmission debugging information

### ISSUE THREAD

**Issue by d4rken** [matomo-org/piwik-sdk-android#228]
- [x] At least the server response code [here](https://github.com/matomo-org/piwik-sdk-android/blob/master/piwik-sdk/src/main/java/org/piwik/sdk/dispatcher/DefaultPacketSender.java#L149)
- [x] Check that additional details are available for both GET and POST, see #231

**Comment by arul-prasad** [comment]
Thanks Matthias, you are right, yesterday i figured it out it is a POST call. 

it will be better to have also the post param in the log. Thanks
