### ISSUE TITLE
Data is not being shown in Matomo dashboard

### ISSUE THREAD

**Issue by sandeshnaroju** [matomo-org/piwik-sdk-android#230]
I have setup my server with Matomo and running successfully with 2 website trackings. I wanted to add analytics for my android application. So created a new website with siteid 4. And added below code in my android app. 

    `public class MyApplication extends PiwikApplication {

    @Override
    public void onCreate() {
        super.onCreate();
        initPiwik();
    }

    private void initPiwik() {
        Timber.plant(new Timber.DebugTree());
        TrackHelper.track().download().identifier(new DownloadTracker.Extra.ApkChecksum(this)).with(getTracker());
    }

    @Override
    public TrackerConfig onCreateTrackerConfig() {
        return TrackerConfig.createDefault("https://analytics.myapp.in/piwik/piwik.php", 4);
    }
    }`

> D/PIWIK:DownloadTrackingHelper: Tracking app download...
   D/PIWIK:Tracker: Event added to the queue: org.piwik.sdk.TrackMe@53f41fc
> D/PIWIK:EventDiskCache: Cache check took 1ms
   D/PIWIK:EventDiskCache: Uncaching of 0 events took 0ms
   D/PIWIK:EventCache: Switched state to ONLINE, uncached 0 events from disk. 
   D/PIWIK:Dispatcher: Drained 2 events.
   V/PIWIK:DefaultPacketSender: Connection open to https://analytics.myapp.in/piwik/piwik.php 
   V/PIWIK:DefaultPacketSender: Transmission successful (code=200). 
   D/PIWIK:Dispatcher: Dispatched 2 events.
   D/PIWIK:EventDiskCache: Cache check took 0ms

Seems like it worked. But I don't see any data in my server dashboard. It still showing the initial page "No data recorded yet" page. Do I have to disable or enable anything to get it work?

**Comment by d4rken** [comment]
Maybe you need to adjust the displayed date range or start data archiving.
Does it show in the live feed?

Based on your logs id say it's a server issue.

**Comment by sandeshnaroju** [comment]
"Only track visits and actions when the action URL starts with one of the above URLs". I have enabled this during site setup. I removed it. Now it is working thanks for the amazing sdk.

**Comment by d4rken** [comment]
Happy to hear it's working.

**Comment by jewelzqiu** [comment]
Hi @d4rken . I am using sdk 4.0.1 and matomo server 3.7.0

from android log, data was posted successfully:
`V/MATOMO:DefaultPacketSender: Transmission finished (code=200).`
And from server log it says (I am using docker image: `matomo:fpm`):
`"POST /index.php" 200`

But matomo web page shows no data
And mysql table `matomo_log_visit` is empty too

"Only track visits and actions when the action URL starts with one of the above URLs" is disabled

Please help...
