### ISSUE TITLE
more log on DefaultPacketSender when events > 1

### ISSUE THREAD

**Issue by arul-prasad** [matomo-org/piwik-sdk-android#231]
**I have full log with track url and query param when events == 1**

11-21 12:50:34.886 11193-11903/com.sella.BancaSella D/PIWIK:Dispatcher: Drained 1 events.
11-21 12:50:34.887 11193-11903/com.sella.BancaSella D/PIWIK:DefaultPacketSender: Connection open to **### https://piwikanalytics.it/piwik.php?rand=61624&idsite=87&rec=1&apiv=1&send_image=0&uid=54acf98a-db23-4621-ad0b-e057c70f50ec&cdt=2018-11-21%2012%3A48%3A34%2B0530&action_name=ContactUs&_id=f0ddbff47790478e&url=http%3A%2F%2Fcom.sella.BancaSella%2FContactUs**
11-21 12:50:35.595 11193-11903/com.sella.BancaSella D/PIWIK:DefaultPacketSender: Transmission successful (code=204).
11-21 12:50:35.595 11193-11903/com.sella.BancaSella D/PIWIK:Dispatcher: Dispatched 1 events.

**where as when events size is > 1 we have only the base url without query param ... able to add log ?**

1-21 12:47:02.231 11193-11652/com.sella.BancaSella D/PIWIK:Dispatcher: Drained 3 events.
**11-21 12:47:02.231 11193-11652/com.sella.BancaSella D/PIWIK:DefaultPacketSender: Connection open to https://piwikanalytics.it/piwik.php**
11-21 12:47:03.001 11193-11652/com.sella.BancaSella D/PIWIK:DefaultPacketSender: Transmission successful (code=204).
11-21 12:47:03.003 11193-11652/com.sella.BancaSella D/PIWIK:Dispatcher: Dispatched 3 events.

**Comment by d4rken** [comment]
Likely because with events > 1 we use POST instead of GET to transmit multiple events at once.

Closing this in favor of #228
